Repository pyhf/pyhf-validation, pull requests merged in 2020-03, with the labels that each got.

#4 docs: Add developer information
  README.md
Labels: documentation

#3 feat: Add scripts for comparing nuisance parameters
  .github/workflows/ci.yml
  MANIFEST.in
  scripts/compare_fitted_nuisance.py
  scripts/compare_nuisance.py
  tests/test_compare_nuisance.sh
Labels: enhancement

#5 docs: Add CodeFactor badge to README
  README.md
Labels: documentation

#6 docs: Add LGTM code quality badge
  README.md
Labels: documentation

#7 refactor: Update pyhf parameter naming scheme
  scripts/compare_fitted_nuisance.py
  scripts/compare_nuisance.py
  tests/test_compare_nuisance.sh
  tests/test_suite.sh
Labels: refactor

#10 refactor: Use source build based ROOT image for base Docker image
  README.md
  docker/Dockerfile
Labels: documentation, refactor

#11 ci: Use official Docker GitHub Action for publication to Docker Hub
  .github/workflows/publish.yml
Labels: CI, Docker

#12 ci: Use the same Docker workflow for testing as publication
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: CI, Docker, fix
